version: '3'

# Root Taskfile orchestrating development tasks. See ./taskfiles for sub-taskfiles.

vars:
  POSTGRES_MAJOR: '{{.POSTGRES_MAJOR | default "17"}}'
  PLV8_VERSION: '{{.PLV8_VERSION | default "3.2.4"}}'
  PLV8_BRANCH: '{{.PLV8_BRANCH | default "r3.2"}}'
  PREBUILT_PLV8_TAG: '{{.PREBUILT_PLV8_TAG | default "18"}}'
  PG_DEV_CONTAINER_NAME: '{{.PG_DEV_CONTAINER_NAME | default "jd-sql-pg-dev"}}'
  PG_IMAGE_NAME_VANILLA: 'jd-sql-pg-vanilla:{{.POSTGRES_MAJOR}}'
  PG_IMAGE_NAME_PLV8: 'jd-sql-pg-plv8:{{.POSTGRES_MAJOR}}'
  PG_IMAGE_NAME_PLV8_PREBUILT: 'jd-sql-pg-plv8-prebuilt:{{.PREBUILT_PLV8_TAG}}'

includes:
  pg: ./taskfiles/postgres-vanilla.yml
  pgplv8: ./taskfiles/postgres-plv8.yml
  spec: ./taskfiles/jd-sql-spec-runner.yml
  jd: ./taskfiles/jd-subproject.yml
  engines: ./taskfiles/engines-stubs.yml

tasks:
  default:
    desc: Show common tasks
    cmds:
      - task -l

  test:
    desc: Run Java integration tests (JUnit + Testcontainers)
    dir: .
    cmds:
      - |
        set -euo pipefail
        if [ -x ./gradlew ]; then
          ./gradlew :test-src:java-tests:test --no-daemon
        else
          gradle :test-src:java-tests:test --no-daemon
        fi

  java:watch-sql:
    desc: Watch SQL and test sources; re-run Java tests on change
    sources:
      - sql/**/*.sql
      - external/jd/spec/test/cases/*.json
      - test-src/java-tests/src/test/java/**/*.java
      - test-src/java-tests/src/test/resources/**/*
    method: none
    silent: true
    cmds:
      - task: test
    watch: true
